version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/golang:latest'
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - v1-pkg-cache
      - run: go mod download
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
